### ISSUE TITLE
Please include a license file

### ISSUE THREAD

**Issue by bochecha** [berdario/resumable-urlretrieve#4]
Most Linux distros require this.

In addition, the MIT license requires it itself.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

https://opensource.org/licenses/MIT

**Comment by berdario** [comment]
The license notice is already in the [README](https://github.com/berdario/resumable-urlretrieve/blob/master/README.md#license)

Isn't this enough for Fedora?

I'm not keen on adding an extra file that doesn't serve any practical purpose, if it's only for bureaucracy

If instead the packaging tools for Fedora expect that file to be there, and barf errors otherwise, it's another matter

**Comment by bochecha** [comment]
That could be enough... except the `README` also isn't included in the tarball. 😃

**Comment by berdario** [comment]
whoops :/

will fix it tonight

thanks for chasing this up

**Comment by berdario** [comment]
Added to the manifest, and uploaded a new tarball to pypi (I did the same for pythonz-bd and pew)

let me know if there's something else that I should fix
